### ISSUE TITLE
.npmrc files are not used

### ISSUE THREAD

**Issue by patrickmarabeas** [renovatebot/pro#45]
No placement of an `.npmrc` is used by Renovate Pro.

- `/home/ubuntu/.npmrc`
- `/home/<user>/.npmrc`
- `<project repo>/.npmrc`

I am able to correctly `npm info <package>` from terminal from within the container.

**Comment by rarkins** [comment]
If you mount `/home/ubuntu/.npmrc` within the Pro's "server" container then it should work, assuming you didn't override the container's `user` (which you shouldn't do). 

Alternative, define `npmrc` as a field within your `config.js`, like:

```js
module.exports = {
  npmrc: '.........'
};
```

Any `.npmrc` found within a repository's file system will also be read, however it is implicitly ignored if Renovate has found an `.npmrc` *config* before that.

**Comment by patrickmarabeas** [comment]
`.npmrc` in home dir is now working. Must have been a permission issue as the container user was being temporarily switched to `root` to install certs.

How dependant is Renovate Pro on the container being run as `ubuntu`?

**Comment by rarkins** [comment]
Renovate Pro is built on Ubuntu 18.04. Apart from `.npmrc` - which is your choice whether to add or not, because there are alternatives - the only other package manager that so far depends on `/home/ubuntu` existing is Gradle.

However later this year I intend to have Pro support individual manager containers like `renovate/gradle` and `renovate/npm` so that it can switch which version of each to use at runtime. i.e. detect the best version of each binary to use via either the repository or config, and then run that exact version, such as `renovate/npm:6.9.0`. In such case it will be a required step that a common uid/guid is used between the containers.

Are you wanting to run it as `root`, or something else?

**Comment by patrickmarabeas** [comment]
Successfully running it as a user within a range that OpenShift provides the project.

**Comment by rarkins** [comment]
I'm going to close this issue because the original topic was resolved. If you have a feature request regarding customisable user ID in the Docker container, please provide details in a new issue so we can discuss there. Pro's current setup is pretty simple - it is based on ubuntu and does have some files it owns in /home/ubuntu. Additionally, in future, for file permissions reasons it will be necessary that the same uid/guid is shared between multiple containers that you won't have control over.
