### ISSUE TITLE
[Question] Is there any way to specify CLI version on renovate server?

### ISSUE THREAD

**Issue by miyajan** [renovatebot/pro#62]
Now the CLI version seems to be fixed on the server of renovate pro.

I know that it is for stability of Enterprise users. But there is a case that I want to use the latest feature of renovate CLI on my responsibility.

So it will help if I can specify CLI version of renovate pro (e.g. by docker environment variable). Is there any way to do it?

**Comment by rarkins** [comment]
The `renovate/pro:next` tag has been intended for always having the latest released Renovate OSS. However right now it’s possibly “broken”.

But this is not intentional and I plan to put steps in place to try to reduce the chance it breaks in `next`.

It won’t be possible to specify the exact Renovate version but I assume latest is hopefully ok. 

Can you test with `0.16.0-pre.2`?
