### ISSUE TITLE
Scans reaching some invisible limit on big organizations

### ISSUE THREAD

**Issue by elpaisa** [renovatebot/pro#80]
Hi, this might not be a renovate issue but a configuration one, the thing is that we have over 2000 repositories to be scanned by a single renovate instance, which has enough resources to compute that batch, but according to logs we can see it is scanning about 400 repos every hour

**Comment by rarkins** [comment]
There isn't any artificial limitation in place. However Pro runs sequentially, i.e. one repo at a time, so 400 repos per hour means one every 9 seconds and I would not be surprised if that's correct. Currently we don't have any distribution that processes repositories in parallel or supports horizontal scaling.

**Comment by rarkins** [comment]
Update: we will be releasing horizontal scalability for self-hosted Renovate in Q1/2020 but due to its complexity it will be available only in [WhiteSource for Developers](https://www.whitesourcesoftware.com/whitesource-for-developers/). For anyone interested in learning about how this is packaged and priced, please fill out https://renovate.whitesourcesoftware.com/contact-us/ and describe this issue so they can put you in touch with the right person.
